services:
  mysql:
    image: mysql:8.0
    container_name: ecoride-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride
      MYSQL_PASSWORD: ecoride
      TZ: Europe/Paris
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ecoride-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    ports:
      - "8081:80"
    depends_on:
      - mysql

  mongo:
    image: mongo:7
    container_name: ecoride-mongo
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: ecoride-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8082:8081"
    depends_on:
      - mongo

  php:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ecoride-php
    working_dir: /var/www/api
    volumes:
      - ./api:/var/www/api
    depends_on:
      - mysql
      - mongo

  nginx:
    image: nginx:alpine
    container_name: ecoride-nginx
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/api:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  mysql_data:
  mongo_data:
